production: &production
  access_key_id: <%= ENV['AMAZON_KEY'] %>
  secret_access_key: <%= ENV['AMAZON_SECRET'] %>
  bucket: <%= ENV['S3_BUCKET'] %>
  secure: true
  endpoint: s3-ap-northeast-1.amazonaws.com

development:
 <<: *production
